# Reanalysis of published scRNA-seq data using LN's t-test
Here we assess how the commonly used t-test on log-normalized scRNA-seq data for differential expression (DE) impacts biological conclusions drawn from those data, by comparing it with LN's t-test. To do this, we check whether a gene set enrichment analysis (GSEA) on the results of both DE methods are qualitatively different.
We follow the guidelines in the "Single-cell best practices" book (Heumos, L., Schaar, A.C., Lance, C. et al., 2023).

In [1]:
import scanpy as sc
import gseapy as gp

## Pre-processing

In [2]:
adata = sc.read(
    "kang_counts_25k.h5ad", backup_url="https://figshare.com/ndownloader/files/34464122"
)
adata

AnnData object with n_obs × n_vars = 24673 × 15706
    obs: 'nCount_RNA', 'nFeature_RNA', 'tsne1', 'tsne2', 'label', 'cluster', 'cell_type', 'replicate', 'nCount_SCT', 'nFeature_SCT', 'integrated_snn_res.0.4', 'seurat_clusters'
    var: 'name'
    obsm: 'X_pca', 'X_umap'

In [3]:
# Storing the counts for later use
adata.X = adata.X.toarray()
# Renaming label to condition
adata.obs = adata.obs.rename({"label": "condition"}, axis=1)
adata.obs["group"] = adata.obs.condition.astype("string") + "_" + adata.obs.cell_type.astype("string")

# Normalizing
sc.pp.normalize_total(adata)
adata_norm = adata.copy()
sc.pp.log1p(adata)

In [4]:
celltype_condition = "stim_FCGR3A+ Monocytes"  # 'stimulated_B',  'stimulated_CD8 T', 'stimulated_CD14 Mono'

## DE and GSEA following [sc-best-practices](https://www.sc-best-practices.org/conditions/gsea_pathway.html)

In [5]:
sc.tl.rank_genes_groups(adata, "group", method="t-test", key_added="t-test", corr_method="bonferroni")

In [6]:
df = sc.get.rank_genes_groups_df(adata, celltype_condition, key="t-test")
# Number of significant genes (e.g., FDR < 0.05)
n_significant = (df["pvals_adj"] < 0.05).sum()
print(f"Number of significant genes (FDR < 0.05): {n_significant}")

Number of significant genes (FDR < 0.05): 4687

In [7]:
log1p_rnk = sc.get.rank_genes_groups_df(adata, celltype_condition, key="t-test")
log1p_rnk

         names      scores  logfoldchanges          pvals      pvals_adj
0       IFITM3  123.019180        3.847020   0.000000e+00   0.000000e+00
1        ISG15  119.732079        3.764381   0.000000e+00   0.000000e+00
2       TYROBP   91.894241        3.043695   0.000000e+00   0.000000e+00
3      TNFSF10   87.408890        3.685921   0.000000e+00   0.000000e+00
4      S100A11   85.721817        2.467858   0.000000e+00   0.000000e+00
...        ...         ...             ...            ...            ...
15701     NPM1  -57.033661       -3.380572  8.037546e-303  1.262377e-298
15702    ITM2A  -57.096916       -6.033978   0.000000e+00   0.000000e+00
15703   OCIAD2  -62.463715       -4.942270   0.000000e+00   0.000000e+00
15704      CD7  -62.999275       -4.852872   0.000000e+00   0.000000e+00
15705     CD3D  -68.085533       -4.853330   0.000000e+00   0.000000e+00

[15706 rows x 5 columns]

In [8]:
log1p_gsea = gp.prerank(rnk=log1p_rnk[["names", "scores"]], # or rnk = rnk,
                     gene_sets='KEGG_2016',
                     threads=4,
                     min_size=5,
                     max_size=1000,
                     permutation_num=1000, # reduce number to speed up testing
                     outdir=None, # don't write to disk
                     seed=6,
                     verbose=True, # see what's going on behind the scenes
                    )

2026-01-16 12:16:41,105 [WARNING] Duplicated values found in preranked stats: 0.01% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-01-16 12:16:41,106 [INFO] Parsing data files for GSEA.............................
2026-01-16 12:16:41,114 [INFO] Enrichr library gene sets already downloaded in: /Users/pedroferreira/.cache/gseapy, use local file
2026-01-16 12:16:41,121 [INFO] 0004 gene_sets have been filtered out when max_size=1000 and min_size=5
2026-01-16 12:16:41,122 [INFO] 0289 gene_sets used for further statistical testing.....
2026-01-16 12:16:41,122 [INFO] Start to run GSEA...Might take a while..................
2026-01-16 12:16:43,969 [INFO] Congratulations. GSEApy runs successfully................

In [9]:
log1p_gsea.res2d[log1p_gsea.res2d["FDR q-val"] < 0.05].sort_values("FDR q-val")

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,Ribosome Homo sapiens hsa03010,-0.873782,-2.658311,0.0,0.0,0.0,84/126,4.97%,RPL13;RPL3;RPL5;RPS3A;RPL7;RPS3;RPLP0;RPL13A;R...
1,prerank,Phagosome Homo sapiens hsa04145,0.634326,2.493972,0.0,0.0,0.0,51/124,8.15%,FCGR3A;CTSS;HLA-DPA1;HLA-E;HLA-C;HLA-DRA;HLA-D...
2,prerank,Staphylococcus aureus infection Homo sapiens h...,0.738026,2.349455,0.0,0.0,0.0,20/43,6.33%,FCGR3A;C3AR1;HLA-DPA1;CFD;HLA-DRA;HLA-DRB1;HLA...
3,prerank,Leishmaniasis Homo sapiens hsa05140,0.641486,2.29288,0.0,0.0,0.0,23/65,4.70%,FCGR3A;HLA-DPA1;HLA-DRA;HLA-DRB1;CYBA;NCF1;HLA...
4,prerank,Tuberculosis Homo sapiens hsa05152,0.595008,2.26937,0.0,0.0,0.0,42/148,5.80%,FCGR3A;FCER1G;CTSS;HLA-DPA1;CD74;HLA-DRA;HLA-D...
5,prerank,RIG-I-like receptor signaling pathway Homo sap...,0.663737,2.268581,0.0,0.0,0.0,11/52,4.20%,ISG15;CXCL10;IRF7;DDX58;IFIH1;TANK;NFKBIA;DHX5...
6,prerank,Influenza A Homo sapiens hsa05164,0.571049,2.254096,0.0,0.0,0.0,39/144,6.10%,TNFSF10;CXCL10;IRF7;OAS1;MX1;HLA-DPA1;RSAD2;HL...
15,prerank,T cell receptor signaling pathway Homo sapiens...,-0.663031,-1.967567,0.0,0.0,0.0,25/96,8.86%,CD3D;LAT;CD3E;CD247;LCK;CD8A;CD3G;FYN;CD8B;JUN...
20,prerank,Primary immunodeficiency Homo sapiens hsa05340,-0.72165,-1.864955,0.0,0.000743,0.004,13/32,5.87%,CD3D;CD3E;LCK;IL7R;CD8A;CD8B;CD79A;ICOS;TNFRSF...
19,prerank,Ribosome biogenesis in eukaryotes Homo sapiens...,-0.648363,-1.868378,0.0,0.00099,0.004,31/73,15.03%,NOP58;NHP2;IMP3;NHP2L1;POP5;SBDS;NOB1;RPP40;WD...
7,prerank,Lysosome Homo sapiens hsa04142,0.551454,2.168785,0.0,0.001525,0.004,34/115,7.54%,CTSS;PSAP;NPC2;CTSC;CD68;CTSL;SCARB2;LAPTM5;LA...
9,prerank,Osteoclast differentiation Homo sapiens hsa04380,0.531116,2.08327,0.0,0.005633,0.018,36/122,5.51%,TYROBP;FCGR3A;LILRB2;SPI1;CYBA;NCF1;JUNB;LILRA...
8,prerank,Mineral absorption Homo sapiens hsa04978,0.6811,2.093977,0.0,0.00567,0.016,10/32,6.84%,FTH1;MT2A;FTL;ATP1B3;HMOX1;SLC8A1;ATOX1;SLC31A...
11,prerank,Antigen processing and presentation Homo sapie...,0.57786,2.062821,0.0,0.006792,0.027,19/66,2.11%,CTSS;HLA-DPA1;HLA-E;HLA-C;CD74;HLA-DRA;HLA-DRB...
10,prerank,Asthma Homo sapiens hsa05310,0.738916,2.067479,0.005435,0.007204,0.026,7/19,3.72%,FCER1G;HLA-DPA1;HLA-DRA;HLA-DRB1;HLA-DPB1;CD40...
12,prerank,Systemic lupus erythematosus Homo sapiens hsa0...,0.541032,2.030045,0.0,0.010229,0.041,21/94,5.00%,FCGR3A;HLA-DPA1;H3F3B;CD86;HLA-DRA;SSB;HLA-DRB...
13,prerank,Viral myocarditis Homo sapiens hsa05416,0.595928,2.000753,0.0,0.011905,0.052,15/52,3.52%,HLA-DPA1;HLA-E;HLA-C;CD86;HLA-DRA;HLA-DRB1;BID...
14,prerank,Salmonella infection Homo sapiens hsa05132,0.536367,1.979001,0.0,0.013913,0.065,25/74,6.46%,CASP1;ACTB;ARPC5;ARPC2;ARPC1B;ARPC3;CCL3;RAC1;...
16,prerank,Toll-like receptor signaling pathway Homo sapi...,0.506573,1.932306,0.0,0.020457,0.099,26/88,8.75%,CXCL10;IRF7;CXCL11;CD86;CD40;CCL3;RAC1;NFKBIA;...
18,prerank,Herpes simplex infection Homo sapiens hsa05168,0.476535,1.899671,0.0,0.024486,0.13,40/160,5.50%,IFIT1;IRF7;OAS1;HLA-DPA1;PILRA;HLA-E;HLA-C;CD7...
17,prerank,Hepatitis C Homo sapiens hsa05160,0.512064,1.910004,0.0,0.024515,0.124,19/98,4.78%,IFIT1;IRF7;OAS1;DDX58;OAS2;GRB2;OAS3;NFKBIA;EI...
26,prerank,Protein export Homo sapiens hsa03060,-0.703269,-1.700597,0.003663,0.030158,0.167,15/23,19.56%,SEC62;SRPRB;HSPA5;SPCS1;SRP72;SEC11C;OXA1L;IMM...
23,prerank,Fc gamma R-mediated phagocytosis Homo sapiens ...,0.500609,1.84181,0.0,0.031886,0.184,19/85,5.70%,FCGR3A;LYN;ARPC5;NCF1;VASP;ARPC2;ARPC1B;ARPC3;...
22,prerank,Shigellosis Homo sapiens hsa05131,0.517891,1.846492,0.0,0.032863,0.179,20/59,10.66%,ACTB;ARPC5;ARPC2;ARPC1B;ARPC3;RIPK2;RAC1;WAS;N...
21,prerank,Toxoplasmosis Homo sapiens hsa05145,0.487715,1.855663,0.0,0.033206,0.173,28/103,6.70%,HLA-DPA1;HLA-DRA;HLA-DRB1;HSPA1A;HSPA8;HLA-DPB...
28,prerank,Propanoate metabolism Homo sapiens hsa00640,-0.662356,-1.666614,0.001192,0.045807,0.275,13/29,17.39%,LDHB;LDHA;PCCB;ACACA;BCKDHB;ECHDC1;ACSS1;HIBCH...
31,prerank,Pyruvate metabolism Homo sapiens hsa00620,-0.642006,-1.655903,0.002384,0.046479,0.32,15/34,16.69%,LDHB;MDH1;LDHA;PKM;HAGHL;ACACA;ACYP1;GLO1;ACSS...

## DE and GSEA using LN's t-test

In [16]:
import importlib
import os

file_path = os.path.join(os.getcwd(), "../../pkg/", "scanpy_wrapper.py")
spec = importlib.util.spec_from_file_location("scanpy_wrapper", file_path)
scanpy_wrapper = importlib.util.module_from_spec(spec)
spec.loader.exec_module(scanpy_wrapper)

# LN's t-test uses normalized data without log1p
scanpy_wrapper.rank_genes_groups_ln(adata_norm, "group", key_added="lnt-test", groups=[celltype_condition])

Processing group: stim_FCGR3A+ Monocytes

In [17]:
df = sc.get.rank_genes_groups_df(adata_norm, celltype_condition, key="lnt-test")
# Number of significant genes (e.g., FDR < 0.05)
n_significant = (df["pvals_adj"] < 0.05).sum()
print(f"Number of significant genes (FDR < 0.05): {n_significant}")

Number of significant genes (FDR < 0.05): 2161

In [18]:
ln_rnk = sc.get.rank_genes_groups_df(adata_norm, celltype_condition, key="lnt-test")
ln_rnk

         names     scores  logfoldchanges  pvals  pvals_adj
0        MS4A7  95.427521        4.257463    0.0        0.0
1       IFITM3  89.460434        2.614924    0.0        0.0
2      TNFSF10  82.742287        2.827140    0.0        0.0
3       FCGR3A  82.528114        4.222550    0.0        0.0
4       MS4A4A  75.845924        5.423291    0.0        0.0
...        ...        ...             ...    ...        ...
15701     RPS3 -47.933701       -1.904445    0.0        0.0
15702    RPL10 -47.992931       -1.508253    0.0        0.0
15703     RPS6 -48.056728       -1.929161    0.0        0.0
15704     RPL3 -51.473209       -2.319095    0.0        0.0
15705    RPL13 -53.769817       -1.968376    0.0        0.0

[15706 rows x 5 columns]

In [19]:
ln_gsea = gp.prerank(rnk=ln_rnk[["names", "scores"]], # or rnk = rnk,
                     gene_sets='KEGG_2016',
                     threads=4,
                     min_size=5,
                     max_size=1000,
                     permutation_num=1000, # reduce number to speed up testing
                     outdir=None, # don't write to disk
                     seed=6,
                     verbose=True, # see what's going on behind the scenes
                    )

2026-01-16 12:22:11,226 [WARNING] Duplicated values found in preranked stats: 0.01% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-01-16 12:22:11,227 [INFO] Parsing data files for GSEA.............................
2026-01-16 12:22:11,242 [INFO] Enrichr library gene sets already downloaded in: /Users/pedroferreira/.cache/gseapy, use local file
2026-01-16 12:22:11,257 [INFO] 0004 gene_sets have been filtered out when max_size=1000 and min_size=5
2026-01-16 12:22:11,258 [INFO] 0289 gene_sets used for further statistical testing.....
2026-01-16 12:22:11,259 [INFO] Start to run GSEA...Might take a while..................
2026-01-16 12:22:14,120 [INFO] Congratulations. GSEApy runs successfully................

In [20]:
ln_gsea.res2d[ln_gsea.res2d["FDR q-val"] < 0.05].sort_values("FDR q-val")

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,Ribosome Homo sapiens hsa03010,-0.913684,-3.07798,0.0,0.0,0.0,85/126,2.88%,RPL13;RPL3;RPS6;RPL10;RPS3;RPL13A;RPS18;RPL7;R...
14,prerank,Natural killer cell mediated cytotoxicity Homo...,0.678268,2.060205,0.0,0.0,0.0,30/104,7.93%,TNFSF10;FCGR3A;TYROBP;FCER1G;BID;HLA-E;PTPN6;F...
12,prerank,Complement and coagulation cascades Homo sapie...,0.795423,2.101348,0.0,0.0,0.0,12/46,5.11%,C3AR1;CFD;SERPINA1;SERPING1;PLAUR;C1QA;C1QB;C2...
11,prerank,Influenza A Homo sapiens hsa05164,0.670746,2.102021,0.0,0.0,0.0,35/144,4.86%,TNFSF10;CXCL10;IRF7;OAS1;HLA-DPA1;CASP1;DDX58;...
10,prerank,Systemic lupus erythematosus Homo sapiens hsa0...,0.714395,2.120084,0.0,0.0,0.0,23/94,5.37%,FCGR3A;CD86;HLA-DPA1;SSB;FCGR1A;CD40;FCGR3B;C1...
9,prerank,Parkinson's disease Homo sapiens hsa05012,-0.633657,-2.121617,0.0,0.0,0.0,69/109,16.43%,COX4I1;NDUFS5;PARK7;NDUFA4;ATP5A1;COX7A2L;NDUF...
8,prerank,RNA transport Homo sapiens hsa03013,-0.614256,-2.157499,0.0,0.0,0.0,87/151,20.75%,PABPC1;EEF1A1;EIF4A2;EIF3E;EIF3F;RAN;EIF3G;RNP...
13,prerank,Oxidative phosphorylation Homo sapiens hsa00190,-0.625019,-2.079896,0.0,0.0,0.0,56/105,12.45%,COX4I1;NDUFS5;NDUFA4;ATP5A1;COX7A2L;NDUFB11;AT...
6,prerank,Spliceosome Homo sapiens hsa03040,-0.66114,-2.202439,0.0,0.0,0.0,87/126,19.19%,HNRNPA1;SNRPD2;HNRNPM;SRSF2;SRSF3;NHP2L1;LSM7;...
5,prerank,Tuberculosis Homo sapiens hsa05152,0.699336,2.217008,0.0,0.0,0.0,44/148,7.04%,FCGR3A;FCER1G;CTSS;HLA-DPA1;BID;RIPK2;FCGR1A;L...
4,prerank,Huntington's disease Homo sapiens hsa05016,-0.624868,-2.244742,0.0,0.0,0.0,81/157,16.43%,COX4I1;NDUFS5;NDUFA4;ATP5A1;GPX1;COX7A2L;NDUFB...
3,prerank,Staphylococcus aureus infection Homo sapiens h...,0.843084,2.246846,0.0,0.0,0.0,20/43,5.30%,FCGR3A;C3AR1;CFD;HLA-DPA1;FCGR1A;FCGR3B;C1QA;H...
2,prerank,Phagosome Homo sapiens hsa04145,0.733237,2.277583,0.0,0.0,0.0,45/124,8.03%,FCGR3A;CTSS;NCF1;HLA-DPA1;MSR1;HLA-E;FCGR1A;LA...
7,prerank,Leishmaniasis Homo sapiens hsa05140,0.770025,2.158104,0.0,0.0,0.0,22/65,4.86%,FCGR3A;NCF1;HLA-DPA1;FCGR1A;PTPN6;FCGR3B;CYBA;...
1,prerank,Osteoclast differentiation Homo sapiens hsa04380,0.740875,2.314307,0.0,0.0,0.0,36/122,5.88%,FCGR3A;TYROBP;LILRB2;NCF1;LILRA5;LILRB1;SPI1;F...
17,prerank,Protein export Homo sapiens hsa03060,-0.801919,-2.02778,0.0,0.000093,0.001,17/23,12.64%,SEC62;HSPA5;SPCS1;SRP14;SEC11C;SEC61B;SPCS2;SR...
16,prerank,Toll-like receptor signaling pathway Homo sapi...,0.689977,2.043883,0.0,0.000122,0.001,21/88,5.16%,CXCL10;CD86;IRF7;CXCL11;CD40;TLR1;TLR2;CCL3;CD...
15,prerank,Lysosome Homo sapiens hsa04142,0.670969,2.047296,0.0,0.000134,0.001,31/115,7.11%,CTSS;PSAP;CTSC;NPC2;CD68;SCARB2;LAMP2;CTSL;ASA...
19,prerank,Fc gamma R-mediated phagocytosis Homo sapiens ...,0.682202,1.988399,0.0,0.000516,0.005,16/85,3.09%,FCGR3A;NCF1;LYN;VASP;FCGR1A;ARPC5;HCK;ARPC2;AR...
18,prerank,RIG-I-like receptor signaling pathway Homo sap...,0.747407,1.993832,0.0,0.000559,0.005,11/52,5.25%,ISG15;CXCL10;IRF7;DDX58;IFIH1;TANK;DHX58;TNF;C...
25,prerank,Ribosome biogenesis in eukaryotes Homo sapiens...,-0.615359,-1.913332,0.0,0.000971,0.012,53/73,28.30%,NHP2L1;RAN;IMP3;NOP58;SBDS;NHP2;FBL;GNL3;MPHOS...
20,prerank,Pertussis Homo sapiens hsa05133,0.69621,1.944706,0.0,0.001819,0.018,23/62,7.76%,SERPING1;CASP1;C1QA;C1QB;C2;TNF;MYD88;PYCARD;G...
24,prerank,Rheumatoid arthritis Homo sapiens hsa05323,0.663899,1.919198,0.0,0.002011,0.023,25/79,6.48%,TNFSF13B;CD86;HLA-DPA1;IL15;ATP6V1B2;CTSL;HLA-...
27,prerank,Alzheimer's disease Homo sapiens hsa05010,-0.537288,-1.878991,0.0,0.002015,0.025,58/138,12.45%,COX4I1;NDUFS5;GAPDH;NDUFA4;ATP5A1;COX7A2L;NDUF...
21,prerank,Viral myocarditis Homo sapiens hsa05416,0.716766,1.932971,0.0,0.002056,0.022,15/52,3.93%,CD86;HLA-DPA1;BID;HLA-E;CD40;HLA-C;HLA-DRB1;HL...
23,prerank,Mineral absorption Homo sapiens hsa04978,0.777844,1.920133,0.002053,0.002129,0.023,10/32,5.56%,MT2A;FTH1;ATP1B3;HMOX1;SLC8A1;SLC31A1;FTL;ATOX...
22,prerank,Salmonella infection Homo sapiens hsa05132,0.677381,1.930139,0.0,0.002179,0.023,24/74,7.65%,CASP1;ARPC5;ARPC2;ARPC1B;IFNGR2;WAS;ARPC3;CCL3...
26,prerank,Antigen processing and presentation Homo sapie...,0.674293,1.880974,0.0,0.00374,0.047,20/66,4.76%,CTSS;HLA-DPA1;HLA-E;HLA-C;HSPA1A;HSP90AA1;CTSL...
29,prerank,Intestinal immune network for IgA production H...,0.724112,1.852962,0.004115,0.005682,0.074,13/38,5.18%,TNFSF13B;CD86;HLA-DPA1;CD40;IL15;HLA-DRB1;CD80...
28,prerank,Chemokine signaling pathway Homo sapiens hsa04062,0.581331,1.853866,0.0,0.005899,0.074,41/160,8.71%,CXCL16;CXCL10;CXCL11;NCF1;LYN;GNG5;ARRB2;HCK;W...
35,prerank,RNA polymerase Homo sapiens hsa03020,-0.684085,-1.814822,0.00369,0.006541,0.094,20/30,17.81%,POLR2L;POLR2E;POLR2F;POLR2I;POLR2C;POLR2K;POLR...
30,prerank,Hepatitis C Homo sapiens hsa05160,0.609613,1.831325,0.0,0.008105,0.109,23/98,9.12%,IFIT1;IRF7;OAS1;DDX58;OAS2;OAS3;GRB2;STAT2;TNF...
32,prerank,Asthma Homo sapiens hsa05310,0.825477,1.823787,0.0,0.008379,0.119,7/19,2.97%,FCER1G;HLA-DPA1;CD40;HLA-DRB1;HLA-DPB1;HLA-DRA...
31,prerank,Cytokine-cytokine receptor interaction Homo sa...,0.560134,1.825792,0.0,0.008394,0.115,34/186,6.02%,TNFSF10;CXCL16;CXCL10;TNFSF13B;CXCL11;CD40;IL1...
36,prerank,Herpes simplex infection Homo sapiens hsa05168,0.573794,1.813196,0.0,0.009186,0.146,37/160,6.18%,IFIT1;PILRA;IRF7;OAS1;HLA-DPA1;DDX58;HLA-E;IFI...
33,prerank,Allograft rejection Homo sapiens hsa05330,0.742509,1.816274,0.002105,0.009278,0.137,11/32,2.97%,CD86;HLA-DPA1;HLA-E;CD40;HLA-C;HLA-DRB1;HLA-B;...
34,prerank,Toxoplasmosis Homo sapiens hsa05145,0.602797,1.814976,0.0,0.009282,0.143,27/103,6.83%,HLA-DPA1;CD40;HSPA1A;IFNGR2;HLA-DRB1;TLR2;HSPA...
38,prerank,RNA degradation Homo sapiens hsa03018,-0.574894,-1.772399,0.0,0.010656,0.163,33/71,20.60%,BTG1;PABPC1;ENO1;LSM7;HSPD1;LSM4;HSPA9;LSM2;EX...
37,prerank,Autoimmune thyroid disease Homo sapiens hsa05320,0.735177,1.788537,0.004049,0.013359,0.218,10/31,2.85%,CD86;HLA-DPA1;HLA-E;CD40;HLA-C;HLA-DRB1;HLA-B;...
42,prerank,mRNA surveillance pathway Homo sapiens hsa03015,-0.550274,-1.742292,0.0,0.0136,0.223,38/77,20.04%,PABPC1;PPP2R5C;RNPS1;PPP1CC;RBM8A;SRRM1;NXT1;M...
41,prerank,Pyruvate metabolism Homo sapiens hsa00620,-0.649684,-1.743133,0.005825,0.014571,0.222,14/34,15.73%,LDHB;MDH1;LDHA;PKM;MDH2;PDHB;GLO1;GRHPR;ALDH9A...
39,prerank,Platelet activation Homo sapiens hsa04611,0.592197,1.763014,0.0,0.019186,0.29,18/98,7.28%,FCER1G;LYN;VASP;MYL12A;SNAP23;GUCY1B3;ACTB;GUC...
48,prerank,Non-alcoholic fatty liver disease (NAFLD) Homo...,-0.496142,-1.705545,0.0,0.020585,0.33,49/127,12.45%,COX4I1;NDUFS5;NDUFA4;COX7A2L;NDUFB11;COX6C;JUN...
40,prerank,Measles Homo sapiens hsa05162,0.565768,1.744875,0.001805,0.023462,0.35,23/115,6.02%,TNFSF10;IRF7;OAS1;DDX58;MX1;IFIH1;HSPA1A;IFNGR...
43,prerank,Graft-versus-host disease Homo sapiens hsa05332,0.68542,1.730497,0.004115,0.027246,0.396,11/37,4.13%,CD86;HLA-DPA1;HLA-E;HLA-C;HLA-DRB1;HLA-B;CD80;...
44,prerank,Apoptosis Homo sapiens hsa04210,0.553114,1.72026,0.001727,0.030417,0.44,25/129,6.18%,TNFSF10;CTSS;CTSC;BID;CFLAR;CTSL;BCL2A1;TUBA1B...
45,prerank,Type I diabetes mellitus Homo sapiens hsa04940,0.683958,1.71754,0.008114,0.030795,0.458,10/36,2.97%,CD86;HLA-DPA1;HLA-E;HLA-C;HLA-DRB1;HLA-B;CD80;...
46,prerank,Leukocyte transendothelial migration Homo sapi...,0.591526,1.712224,0.001905,0.031585,0.471,21/86,6.47%,NCF1;VASP;MYL12A;CYBB;CYBA;NCF2;ACTB;ICAM1;CXC...
47,prerank,Endocytosis Homo sapiens hsa04144,0.520651,1.709031,0.0,0.03187,0.486,46/228,8.61%,HLA-E;ARPC5;HLA-C;HSPA1A;RAB8A;SNX2;ARRB2;VPS2...
49,prerank,Cell adhesion molecules (CAMs) Homo sapiens hs...,0.571541,1.704984,0.0,0.032661,0.5,21/94,6.33%,CD86;HLA-DPA1;HLA-E;CD40;HLA-C;HLA-DRB1;HLA-B;...
50,prerank,Arginine and proline metabolism Homo sapiens h...,0.661993,1.699325,0.008368,0.033879,0.521,5/36,1.91%,SAT1;LAP3;CKB;SAT2;CNDP2
51,prerank,Cytosolic DNA-sensing pathway Homo sapiens hsa...,0.627847,1.686184,0.010352,0.038915,0.577,13/49,4.69%,CXCL10;IRF7;CASP1;DDX58;AIM2;MB21D1;CCL4;PYCAR...
52,prerank,Nicotinate and nicotinamide metabolism Homo sa...,0.757021,1.682689,0.011494,0.039499,0.589,5/19,3.55%,NT5C3A;NAMPT;NADK;NT5C2;CD38
53,prerank,Salivary secretion Homo sapiens hsa04970,0.641023,1.669869,0.020202,0.044578,0.634,10/42,7.07%,CST3;ATP1B3;KCNMA1;GUCY1B3;GUCY1A3;CD38;ADCY7;...